version: 2.1
jobs:
  linux:
    parameters:
      rust:
        type: string
      version:
        type: string
      flavor:
        type: string
      test-ssl:
        type: boolean
        default: false
      test-unstable:
        type: boolean
        default: false
    docker:
      - image: rust:<< parameters.rust >>
      - image: << parameters.flavor >>:<< parameters.version >>
        command: mysqld --sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES --max_allowed_packet=32M --ssl
        environment:
          MYSQL_ROOT_PASSWORD: password
    environment:
      DATABASE_URL: mysql://root:password@127.0.0.1:3306/mysql
      RUST_BACKTRACE: full
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: apt install mysql-client
      - run: mysql -uroot -ppassword -e "SELECT @@max_allowed_packet;"
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: deps-<< parameters.rust >>-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - when:
          condition: << parameters.test-ssl >>
          steps:
            - run: cargo test --features ssl
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
      - save_cache:
          key: deps-<< parameters.rust >>-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry/cache
      - when:
          condition: << parameters.test-unstable >>
          steps:
            - run:
                name: Beta
                command: |
                  rustup toolchain install beta
                  cargo +beta test
            - run:
                name: Nightly
                command: |
                  rustup toolchain install nightly
                  cargo +nightly test


workflows:
  test:
    jobs:
      - linux:
          name: stable-mysql-5.6
          rust: latest
          flavor: mysql
          version: "5.6"
          test-ssl: true
      - linux:
          name: stable-mysql-5.7
          rust: latest
          flavor: mysql
          version: "5.7"
          test-ssl: true
      - linux:
          name: stable-mysql-8.0
          rust: latest
          flavor: mysql
          version: "8.0"
          test-ssl: true
          test-unstable: true
      - linux:
          name: stable-mariadb-5.5
          rust: latest
          flavor: mariadb
          version: "5.5"
      - linux:
          name: stable-mariadb-10.3
          rust: latest
          flavor: mariadb
          version: "10.3"
      - linux:
          name: stable-mariadb-10.4
          rust: latest
          flavor: mariadb
          version: "10.4"
